[workspace]
members = [
    "parser",
]
resolver = "2"

[workspace.package]
authors     = ["dalance@gmail.com"]
repository  = "https://github.com/dalance/sdcx"
keywords    = []
categories  = []
license     = "MIT OR Apache-2.0"
readme      = "README.md"
description = ""

[workspace.dependencies]

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
